import { Contact } from "@components/sections";
//import { privacy, terms } from "./desc";
import { MainLayout } from "@layouts";

const PolicyPage = ({ title, content }) => {
  return (
    <div className="policy">
      <div
        className="policy-text"
        dangerouslySetInnerHTML={{ __html: content }}
      />
      <Contact />
    </div>
  );
};

export const getStaticProps = async ({ params }) => {
  const type = params?.type;

  let title = '';
  let content = '';

  if (type === 'privacy') {
    title = 'Privacy Policy';
    content = privacy;
  } else if (type === 'terms') {
    title = 'Terms of Service';
    content = terms;
  } else {
    title = 'Terms of Service';
    content = terms;
    return {
      notFound: true,
    };
  }

  return {
    props: {
      title,
      content,
    },
  };
};

export const getStaticPaths = async () => {
  return {
    paths: [
      { params: { type: 'privacy' } },
      { params: { type: 'terms' } },
    ],
    fallback: false,
  };
};

PolicyPage.getLayout = function getLayout(page) {
  return <MainLayout overflow={false}>{page}</MainLayout>;
};

export default PolicyPage;


const privacy = `<p>AZERUX is a software development company has prepared this Privacy Policy ("Policy") to summarize our online data protection practices. This Privacy Policy contains the reasons for gathering information and what types of it we collect.<br />We collect the personal information, when:<br />&bull;&ensp;When you visit our websites such as www.azerux.com<br />&bull;&ensp;When you contact Azerux by any means like sending an e-mail, filling in the contact form or otherwise<br />&bull;&ensp;When you apply for a job posted on our Website.</p>
<p>The Privacy Policy explains how the information you pass on our websites would be used and how you, as a data subject, can control the usage of your private data and how to communicate with us related to this subject if needed. Our Privacy Policy explains the use of cookies of our Website as well.<br />&nbsp;<br />&bull;&ensp;We kindly recommend to read this Policy before you start using this Website. Your data would be processed only the way it is described in this Privacy Policy. None of our Websites is meant to be used by kids under 16, and we do not collect kids' data of this age group meaningly.<br />&bull;&ensp;The Privacy Policy, which you can read below, is an inherent part of this Website's Terms of Use. This Policy might be updated at any time in the future, so you should reread it, sometimes checking for updates.<br />&bull;&ensp;If you want to ask any questions or comment on our privacy policy, contact us via office@AZERUX.com</p>
<p>WHAT IS THE RELATION OF Azerux TO YOUR DATA?</p>
<p>&bull;&ensp;By the EU General Data Protection Regulation(abbreviated "GDPR"), Azerux has a right to process and control the personal data transmitted through this Website or gathered in other ways. As a controller, we have a right to decide the means to hold or use your personal information.<br />&bull;&ensp;For recruitment processing services, Azerux resorts a third-party. When you submit an online application to any vacancies posted on the Website, you automatically agree to submit your data, CV, and contacts, including the other information you upload. By filling in the recruitment form, you agree that your data will be collected and processed by our Website. We are the data controller who has a right to process your data in the case of uploading your details.<br /> <br />WHAT TYPE OF DATA ABOUT YOU WE CAN COLLECT?</p>
<p>Only information necessary for allowing you to use the Website or to contact us by any means. This information is used only to a certain extent, which is described in this Privacy Policy.<br />&nbsp;<br />The information which we get from you<br />If you contact us through the e-mail or via the contact form, you leave such personal data, as your name and phone number, e-mail address, communication content, and data associated with it.<br />&nbsp;<br />When you apply for a vacancy, posted on our Website, you leave your full name, e-mail and phone number, your location, and other information you have provided in your CV or applied to it. You might also provide us with the other personal data such as candidates for work you want to recommend us for the position. Periodically, Azerux gets personal information from the third parties from different parts of the globe. This is possible if your data like a CV is published on the job-search Websites, by this giving them the right to use and transmit your data to third parties. We also can get your data if somebody recommended you as a potential employee or another case similar to that. We highly recommend you review the privacy policy of such websites before giving your data to them.<br />&nbsp;<br />Information we obtain when you use and visit our Websites<br />&nbsp;<br />When you visit our Websites, the following information about you might be collected:<br />Information about the devices with the help of which you browse the websites. We obtain such information is the OS version or the hardware model.<br />&nbsp;<br />Your visit's information and the use of our Website, which includes your IP address, location where you are geographically, type and version of the browser, the paths you use to navigate the Website, the pages you view, and the referral source.<br />&nbsp;<br />Your cookies. If you want to get more information about the cookies used on this Website and how you can avoid them, scroll to the "WHAT ARE COOKIES AND HOW DO WE USE THEM" section in this Privacy Policy.</p>
<p>WHY DO WE HAVE TO PROCESS YOUR PERSONAL INFORMATION?</p>
<p>Your data would be processed by us only in cases when we have a legal right to do so.<br />The legal basis will depend on the reasons we have gathered your personal data and on the need to use it. Your personal data might be processed for the following purposes:</p>
<p>&bull;&ensp;You have agreed to a request on our Website to use your personal data.<br />&bull;&ensp;The need for it lays in our legitimate business interests.<br />&bull;&ensp;A legal obligation needed to be complied by us.<br />&bull;&ensp;To be more specific, personal data you submit through this Website and personal information we collect from you, public sources or the third parties will be used on the legal grounds.</p>
<p>Communications, which are based on Azerux legitimate business interest, art 6 paragraph 1 f GDPR:<br />If you ever contacted us through one of the websites listed above, your data might have been processed to enable the possibility of answering your questions, organizing a call, a meeting, a zoom, or communication which occurred the other way. Kindly note that the conversation might be recorded and stored by Azerux company representative in Azerux corporate system.</p>
<p>Marketing and public relations, based on your consent, art. 6 para. One a GDPR:<br />Being a visitor of our Website, utilizing cookies, your personal data might be processed by us to execute marketing research, analyzing the characteristics of the visitors of this Website, accessing the impact of the marketing communication, adjusting it to the tendencies we have detected and planning our future marketing strategies based on their effectiveness, to target our advertising and prepare the analytical report based on the obtained data.<br />&nbsp;<br />As our subscriber, you might have a wish to receive our marketing materials. The data you gave to us might be used to send you promotional materials, announcements about our updates connected to our services, and sending you notifications by e-mail, and newsletters.</p>
<p>&nbsp;Recruitment<br />a) Based on your consent, art. 6 para. 1 a GDPR:<br />If you are a potential employee who sent the data to us, your personal data might be processed by us to assist you with employment, ongoing at the moment, or in the future when the position you selected is vacant. We might use your data to enable the opportunity to submit your resume, apply for online jobs.<br />&nbsp;<br />b) Based on Azerux legitimate interest, art. 6 para. 1 f GDPR:<br />In some particular cases (only upon the request of our clients), your CV might be shown to a potential client for more significant business engagement or to a current client to confirm the correspondence of the level of skills of the potential candidate providing the services. Moreover, to fulfil the compliance obligations, our client may need to check your biography and professional way more precisely before the access to the protected data and facilities would be given. This way, we may ask the following information from you:<br />&nbsp;<br />1. Criminal record<br />2. Tax number<br />3. Work permission<br />4. Citizenship<br />5. Any additional background checks required by particular clients, so you, as an employee, can get access to the clients' premises and systems.</p>
<p>Business relations, based on Azerux's legitimate interest, art. 6 para. 1 f GDPR:<br />Being a representative of our current or potential client, business partner or vendor, your personal data might be processed for the next aims:<br />&nbsp;<br />&bull;&ensp;Organization of an approval<br />&bull;&ensp;Promotion of our new products, works and services<br />&bull;&ensp;Confirmation of the level of our works and services<br />&bull;&ensp;Sending you an invitation to the meetings and events which we organize<br />&bull;&ensp;Documentation signing contracts, invoices or acts or other contractual documents.<br />&nbsp;<br />Need for compliance with economic sanctions and export control list screening, fraud prevention and anti-money laundering, regulators' requirements, and other requirements related to anti-corruption, industry standards.</p>
<p>Corporate and investor relations, based on Azerux compliance obligations, art. 6 para. 1 c GDPR:<br />Being a current or a potential top manager or a director of Azerux, we might process the personal information of yours into:</p>
<p>&bull;&ensp;Organize the possibility to participate in corporate meetings, business trips and events<br />&bull;&ensp;Maintain our corporate records and make obligatory public disclosures and reports<br />&bull;&ensp;Present the company and its management during the sale process performing the other legal obligations<br />&bull;&ensp;Execute the auditor's requests<br />&bull;&ensp;Pay your remuneration<br />&bull;&ensp;Cover related expenses.</p>
<p>This information could be shared via Azerux, and partially provided the banks or notary, payroll agencies or legal advisors to open a corporate bank account or other types of accounts.<br />&nbsp;<br />Being a current or a potential affiliate of Azerux, your private data might be gathered to:</p>
<p>&bull;&ensp;Perform the execution of the auditors' requests and perform other legal obligations, which include anti-money laundering requirements and disclosure of beneficiaries<br />&bull;&ensp;Perform the organization of your participation in corporate meetings and events<br />&bull;&ensp;Provide you with our reports and meeting materials<br />&bull;&ensp;Support you in your rights being executed</p>
<p>Security, based on Azerux's legitimate interest, art. 6 para. 1 f GDPR:<br />Being a visitor of this Website, your personal data might be processed to keep this Website secure, prevent fraud, protect the rights and interests of Azerux and third parties, and protect intellectual property rights.<br />Being a visitor to our office, your data might be processed to ensure our office's security, preventing and detecting any crime, incident, accident, or misconduct.</p>
<p>HOW CAN WE USE YOUR PERSONAL DATA?</p>
<p>Your data might be used by us via:</p>
<p>&bull;&ensp;Collecting<br />&bull;&ensp;Adapting or altering<br />&bull;&ensp;Recording<br />&bull;&ensp;Storing<br />&bull;&ensp;Using<br />&bull;&ensp;Structuring<br />&bull;&ensp;Organizing<br />&bull;&ensp;Retrieving<br />&bull;&ensp;Aligning or combining<br />&bull;&ensp;Consulting<br />&bull;&ensp;Erasing or destruction.</p>
<p>As an international company, your data might be disclosed via transmission, dissemination, or making it available any other way. Your data could be transmitted between the Azerux offices only to the extent permitted by applicable data protection laws. This way, it could be processed in the European Economic Area and outside of it, depending on why we need to process your personal data.<br />&nbsp;<br />Such transmission and processing of personal information are allowed only if this is necessary for the purposes stated in this Policy within the legitimate interest of Azerux.<br />&nbsp;<br />Your data might be disclosed to some of our clients for the business engagement aim to confirm the high level of skills of our team members, auditors, and other external service providers to perform our contractual obligations.<br />&nbsp;<br />Your personal information might also be disclosed:</p>
<p>&bull;&ensp;To the extent when we are required to do this way by law regulations<br />&bull;&ensp;Connected to any prospective or ongoing legal proceedings<br />&bull;&ensp;Establishing or defending our legal rights, which includes providing information to others to prevent fraud or credit risk reduction.</p>
<p>HOW CAN YOU CONTROL YOUR DATA?</p>
<p>As a Data Subject, you have a right to:<br />&nbsp;<br />&bull;&ensp;Requesting whether the personal data of yours is stored in our sources, and if so, what type of information is it, and why we hold this data or how we use it.<br />&bull;&ensp;You can request access to your data, which would enable you to get a copy of the personal information we hold about you, so you can check that we are lawfully processing your data.<br />&bull;&ensp;You can request us to correct the personal information which we hold about you. This allows any incorrect information which we hold about you to be fixed and completed the needed way.<br />&bull;&ensp;You can request for your personal data to be deleted when there is no reason to continue storing your data. Besides, you have a right to request deleting your personal data when you have exercised your right to object to processing (see below).<br />&bull;&ensp;You have an opportunity to oppose the processing of your personal information in cases where we rely on a legitimate interest (or a third party). In your particular situation, you want to object to processing your data. You also have such a right of an objection when your data is processed for direct marketing aims.<br />&bull;&ensp;You have a right to request for your personal data to be processed. This would enable you to ask us to suspend the processing of personal data of yours, e.g., if you want us to reason the need to handle it.<br />&bull;&ensp;You can request a transfer of your personal data in an electronic and structured form to you or another party. This will enable you to get your data in an electronic format if you want to transfer it to another party in an electronic format.<br />&bull;&ensp;You can withdraw consent. You can remove your consent for the transfer, collection, or processing of your personal information for a specific purpose at any time. Once we got a notification that you want to withdraw your consent, your data won't be processed by us any more. It could only be processed if we have a legitimate basis to do so in law. The consent's withdrawal won't influence the lawfulness of processing based on it before consent's removal.<br />&bull;&ensp;In case you want to discuss or exercise any of these rights, please contact us via office@AZERUX.com. The response time of a request is within one month.<br />&bull;&ensp;We also may need to request some specific data from you to help us to confirm your identity, ensuring your right to access the data or to exercise any of your other rights connected with them. This security measure ensures that your data won't get into the hands of anyone who has no legal rights to access it.</p>
<p>Please, wisely exercise your rights and note that their abuse may cause your liability.</p>
<p>HOW YOUR IS DATA RETAINED?</p>
<p>We make sure that the appropriate technical and physical security measures are taken to protect the personal information, which is processed, stored, or transmitted by us. The data is protected from an accidental or unlawful destruction, access or alteration, unauthorized non-legitimate disclosure, and loss.<br />&nbsp;<br />Your data is stored on Azerux's services securely. You can be sure that we won't retain your data for longer than needed to serve the aim of why your data is being processed. To decide the appropriate retention period, the amount, sensitivity and nature of the personal information is considered. We also consider the purposes for which we did process your personal data and whether we can reach them in other ways. In our consideration also comes the period, for which we might need to retain the personal data for meeting our legal obligations or dealing with complaints, queries, or in order of our legal rights to be protected in the case of a claim being made. When we don't need your personal data any more, we will securely erase it.<br />&nbsp;<br />Your personal data is securely stored on the servers of Azerux.<br />Consider that the following information will be retained to the extent that we are required to do so by law and if the provided information is relevant to any prospective and ongoing legal proceedings.<br />&nbsp;<br />&bull;&ensp;Documents<br />&bull;&ensp;Electronic documents, containing personal data<br />&nbsp;<br />This is done to establish, exercise, or defend our legal rights, which include providing the information to others to prevent fraud and reduce credit risk.</p>
<p>WHAT ARE COOKIES AND HOW DO WE USE THEM?</p>
<p>When you visit the Azerux websites, Azerux may place cookies and similar codes to analyze the user's actions (collectively, "Cookies") on your device, browser of the webpage you are using, for personalizing your experience, and understanding usage patterns, improving and securing the Azerux website. Cookies are computer files consist of text. They do not typically contain any information that can identify someone personally, but the personal data that we store about you could be obtained from cookies.<br />&nbsp;<br />Our Website uses different types of cookies, as follows:</p>
<p>&bull;&ensp;Analytical cookies and other types of cookies help us to improve our websites and collect the information anonymously. The type of information we get is how the visitors use our Websites and their features. Examples of such cookies are SID, PHPSESSID, wp-settings-X, wp-settings-time-X, etc.<br />&bull;&ensp;Functional cookies &ndash; they are essential to allow you to move around Azerux websites using their features at full. Functional cookies enable the users to view the Website and use it properly. These cookies also give you access to the secured part of the Azerux websites.<br />&nbsp;<br />Third-party cookies &ndash; such type of cookies helps the third parties to manage and track the effectiveness of their websites, ads, and numbers of visitors. Information about the third parties cookies is available on the relevant Website of theirs. The examples of third-party cookies are cookie, sb, fr, spin, wd, xs, etc.<br />Based on validity, the cookies from Azerux websites may exist in the form of persistent or session cookies.<br />&nbsp;<br />The first one will be stored by a web browser and remain valid until its set expiry date unless it deletes them before this expiry date. A session cookie will expire at the end of using our Website when the user closes the browser. If you want to get more information about what types of Cookies we use, please contact us.<br />Your browser settings can be adjusted to delete some of the cookies from our Website or the third-parties cookies. You can also change your browser settings to prevent the websites from setting cookies or third-party cookies. If you block our Website from the using cookies, you may find that some of its functions are not available, or the specific parts of the Azerux Website will not load.&nbsp;</p>
<p>DO YOU HAVE ANY QUESTIONS?</p>
<p>If you have any questions about this Privacy Policy, please contact us at any time via sales@azerux.com</p>`;


const terms = `<p>These terms and conditions are applied to your usage of Azerux.com Website (further &ndash; the "Site"). Azerux and its affiliates provide the following Terms and conditions. Azerux is not responsible for the information's accuracy, which is posted on the Azerux's Site. Azerux has a right reserved to change any of the information displayed on this Site, and this includes the terms and conditions as well. In case if we make any changes, we publish the newly revised versions on this Site with an updated publication date. As a user, you won't get a direct notification about the revision of the documents, so we kindly ask you to check all the information connected with your situation so you can keep being informed about their state. For obtaining more information about how we use Cookies and learning about our online privacy, please see the Privacy Policy.</p>
<p>DISCLAIMER OF WARRANTY</p>
<p>All materials contained in this document are meant to be "AS IS" and don't have any warranty. Azerux denies warranties of any kind, which include:</p>
<p>&bull;&ensp;Guarantees regarding the availability<br />&bull;&ensp;Warranties related to availability&nbsp;<br />&bull;&ensp;All the possible conditions of merchantability which could be express or implied<br />&bull;&ensp;Fitness for a particular purpose<br />&bull;&ensp;Content accuracy/Data accuracy and other information.</p>
<p>AZERUX does not provide a warranty that the Site, or its content, or its functions and features would be error-free, timely, and secure, or if any defects exist, they would be corrected. Azerux is not responsible for any errors or malfunctions of the Site, including the crashes or any adverse events. If any materials downloaded from the Site damage your computer or cause a loss of data, you are responsible for this at your own risk. Being dissatisfied with the Site or functions which the Site has, you can abstain from using it.</p>
<p>LIMITATION OF LIABILITY</p>
<p>AZERUX is not liable for any kind of damages under no circumstances (damages which are consequential or indirect which may include loss of profits) which are a result of the use of the Site's information or materials, even in the case of Azerux being informed of the probability of such harm.</p>
<p>USER CONDUCT</p>
<p>When using the Site, you should not do the next things:</p>
<p>&bull;&ensp;You should not upload, transmit, and post or publish any materials from the Site that violate that contravenes of any Terms<br />&bull;&ensp;You should not get engaged in spamming and flooding<br />&bull;&ensp;You should not restrict other users from using the Site<br />&bull;&ensp;You should not conduct yourself or other users in a way that could be counted as a criminal offence&nbsp;<br />&bull;&ensp;You should not exploit any of the information obtained from the Website for commercial purposes ( when not allowed by the provider of these materials)<br />&bull;&ensp;It would be best if you did not access the other computer systems in an unauthorized way through this Site.</p>
<p>AZERUX has a right reserved, which does not mean any obligation though, to monitor the Site and to disclose any information, as Azerux considers it necessary to satisfy laws and regulations, which include the government requests to operate the Azerux Website properly, protecting ourselves and our users from the things which Azerux decide at its decision. Azerux has a right not to post or remove any information, fully or partially, that we consider unacceptable or inappropriate, which violates these Terms. Azerux may suspend the use of the Site of any users at its discretion.</p>
<p>SOFTWARE DOWNLOADS</p>
<p>Any software you could download from this Site is the material under copyright of Azerux or its suppliers. Such Software should be used in terms of use that comes with the Software. Any use of the Software which doesn't come in terms of use is strictly prohibited.</p>
<p>USE OF CONTENT</p>
<p>All the content which includes information, files, photos, text, graphics, scripting, or any other materials found on the Site, could be used only for non-commercial personal use, in case if you don't retain the copyright and other proprietary signs which materials contain. The Site's usage for commercial purposes is not allowed unless it is agreed with the Azerux representative's expressed consent. You don't need to obtain permission to link to Azerux from any other site, but if you notify us in advance, we would appreciate that.</p>
<p>COPYRIGHT AND TRADEMARKS</p>
<p>We provide Azerux's trademark for the aim of informing you, and by making it available, we do not give a license for using it. The copyright to all materials posted on this Site belongs to the original creator of these materials. The intellectual property remains to Azerux and is not transferred by you.</p>
<p>LINKS TO THIRD-PARTY SITES</p>
<p>The Website might have links to other third-party sites. Azerux has no responsibility for the content of any other site which you could access through this Site. By signing these Terms, you agree and fully acknowledge that Azerux is not responsible for the content of any linked site or any links contained on such a site. References, which you could find on this Site (references to names, products, and services, marks of any third parties or hypertext links) are posted here for user's convenience and do not mean Azerux's support to such sites and their content, ads, products and other materials which you can find on these sites. You acknowledge that Azerux has no responsibility or liability for any loss or damage caused by the use of the sites or services from the linked sites.</p>
<p>APPLICABLE LAWS</p>
<p>AZERUX operates this Site from within Ukraine. Azerux denies the responsibility to use the materials of the Website in other locations, where they might be prohibited. The ones who choose to access the documents despite the risk are responsible in the face of the law. Users should not use and transfer any materials from the Site violating laws and regulations.&nbsp;</p>
<p>QUESTIONS</p>
<p>If you have any questions or inquiries regarding Azerux privacy policy or other legal guidelines, please, do not hesitate to contact us.</p>`    ;